-- ================================
-- ENUM TYPES
-- ================================
-- Đã loại bỏ các kiểu ENUM, thay thế bằng VARCHAR và CHECK constraint

-- ================================
-- Tạo database nếu chưa có, nếu có rồi thì xóa đi tạo lại
-- Thay 'buysellphoneold' bằng tên database bạn muốn nếu cần
DO $$   
BEGIN
    IF EXISTS (SELECT 1 FROM pg_database WHERE datname = 'buysellphoneold') THEN
        EXECUTE 'DROP DATABASE buysellphoneold';
    END IF;
    EXECUTE 'CREATE DATABASE buysellphoneold';
END$$;

\c buysellphoneold

-- ================================
-- 1) users
-- ================================
USE buysellphoneold;

CREATE TABLE users (
                       id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email          VARCHAR(100) NOT NULL UNIQUE,
                       phone          VARCHAR(20)  NOT NULL UNIQUE,
                       password_hash  TEXT         NOT NULL,
                       role           VARCHAR(20) NOT NULL DEFAULT 'customer' CHECK (role IN ('admin','customer','technician')),
                       status         VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','banned')),
                       created_at     TIMESTAMPTZ      NOT NULL DEFAULT now(),
                       updated_at     TIMESTAMPTZ      NOT NULL DEFAULT now()
);

-- ================================
-- 2) addresses
-- ================================
CREATE TABLE addresses (
                           id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                           line1      VARCHAR(150) NOT NULL,
                           ward       VARCHAR(100),
                           district   VARCHAR(100),
                           city       VARCHAR(100),
                           province   VARCHAR(100),
                           country    VARCHAR(100) DEFAULT 'Vietnam',
                           zip        VARCHAR(20),
                           is_default BOOLEAN NOT NULL DEFAULT FALSE
);
-- Chỉ 1 địa chỉ mặc định mỗi user
CREATE UNIQUE INDEX ux_addresses_default
    ON addresses(user_id)
    WHERE is_default = TRUE;

-- ================================
-- 3) brands
-- ================================
CREATE TABLE brands (
                        id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name  VARCHAR(100) NOT NULL UNIQUE,
                        slug  VARCHAR(120) NOT NULL UNIQUE
);

-- ================================
-- 4) models
-- ================================
CREATE TABLE models (
                        id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        brand_id BIGINT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
                        name     VARCHAR(100) NOT NULL,
                        slug     VARCHAR(120) NOT NULL UNIQUE,
                        year     INTEGER CHECK (year >= 2000)
    );
CREATE UNIQUE INDEX ux_models_brand_name ON models(brand_id, name);

-- ================================
-- 5) products
-- ================================
CREATE TABLE products (
                          id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          model_id         BIGINT NOT NULL REFERENCES models(id) ON DELETE RESTRICT,
                          sku              VARCHAR(50) NOT NULL UNIQUE,
                          color            VARCHAR(50),
                          storage_gb       INTEGER CHECK (storage_gb > 0),
                          ram_gb           INTEGER CHECK (ram_gb >= 0),
                          grade            VARCHAR(10) CHECK (grade IN ('A','B','C','D')),
                          condition_note   TEXT,
                          base_price       NUMERIC(12,2) NOT NULL CHECK (base_price >= 0),
                          sell_price       NUMERIC(12,2) NOT NULL CHECK (sell_price  >= 0),
                          status           VARCHAR(20) NOT NULL DEFAULT 'available' CHECK (status IN ('draft','available','reserved','sold','hidden')),
                          warranty_months  INTEGER NOT NULL DEFAULT 0 CHECK (warranty_months >= 0),
                          created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_products_model ON products(model_id);
CREATE INDEX ix_products_status ON products(status);

-- ================================
-- 6) product_media
-- ================================
CREATE TABLE product_media (
                               id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               product_id  BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
                               url         TEXT   NOT NULL,
                               type        VARCHAR(10) NOT NULL DEFAULT 'image' CHECK (type IN ('image','video')),
                               is_primary  BOOLEAN NOT NULL DEFAULT FALSE,
                               sort_order  INTEGER NOT NULL DEFAULT 0
);
-- Mỗi sản phẩm chỉ có 1 ảnh chính
CREATE UNIQUE INDEX ux_product_media_primary
    ON product_media(product_id)
    WHERE is_primary = TRUE;

-- ================================
-- 7) product_diagnostics
-- ================================
CREATE TABLE product_diagnostics (
                                     id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     product_id           BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
                                     report_jsonb         JSONB  NOT NULL DEFAULT '{}'::jsonb,
                                     depreciation_percent NUMERIC(5,2) NOT NULL CHECK (depreciation_percent >= 0 AND depreciation_percent <= 100),
                                     summary              TEXT,
                                     technician_id        BIGINT REFERENCES users(id),
                                     created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_diag_product_created ON product_diagnostics(product_id, created_at DESC);

-- ================================
-- 8) inventories
-- ================================
CREATE TABLE inventories (
                             id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             product_id    BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
                             location      VARCHAR(100) NOT NULL,
                             qty_available INTEGER NOT NULL DEFAULT 0 CHECK (qty_available >= 0),
                             qty_reserved  INTEGER NOT NULL DEFAULT 0 CHECK (qty_reserved  >= 0)
);
CREATE UNIQUE INDEX ux_inventories_unique ON inventories(product_id, location);

-- ================================
-- 9) carts
-- ================================
CREATE TABLE carts (
                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                       status     VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open','checked_out','abandoned')),
                       created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                       updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_carts_user ON carts(user_id);

-- ================================
-- 10) cart_items
-- ================================
CREATE TABLE cart_items (
                            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            cart_id     BIGINT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
                            product_id  BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
                            qty         INTEGER NOT NULL CHECK (qty > 0),
                            unit_price  NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0)
);
CREATE UNIQUE INDEX ux_cart_items_unique ON cart_items(cart_id, product_id);

-- ================================
-- 11) orders
-- ================================
CREATE TABLE orders (
                        id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
                        code                 VARCHAR(50) NOT NULL UNIQUE,
                        status               VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','processing','shipped','completed','cancelled','refunded')),
                        payment_method       VARCHAR(20) NOT NULL DEFAULT 'cod' CHECK (payment_method IN ('cod','bank','e_wallet','card')),
                        payment_status       VARCHAR(20) NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid','paid','partial','refunded')),
                        subtotal             NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),
                        shipping_fee         NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (shipping_fee >= 0),
                        discount             NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount   >= 0),
                        total                NUMERIC(12,2) NOT NULL CHECK (total >= 0),
                        shipping_address_id  BIGINT REFERENCES addresses(id) ON DELETE SET NULL,
                        created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_orders_user_created ON orders(user_id, created_at DESC);

-- ================================
-- 12) order_items
-- ================================
CREATE TABLE order_items (
                             id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id       BIGINT NOT NULL REFERENCES orders(id)   ON DELETE CASCADE,
                             product_id     BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
                             qty            INTEGER NOT NULL CHECK (qty > 0),
                             unit_price     NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
                             warranty_until DATE
);
CREATE UNIQUE INDEX ux_order_items_unique ON order_items(order_id, product_id);

-- ================================
-- 13) coupons
-- ================================
CREATE TABLE coupons (
                         id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         code             VARCHAR(50) NOT NULL UNIQUE,
                         type             VARCHAR(10) NOT NULL CHECK (type IN ('percent','fixed')),
                         value            NUMERIC(10,2) NOT NULL CHECK (value >= 0),
                         max_uses         INTEGER NOT NULL DEFAULT 0  CHECK (max_uses >= 0),
                         used             INTEGER NOT NULL DEFAULT 0  CHECK (used <= max_uses),
                         start_at         TIMESTAMPTZ,
                         end_at           TIMESTAMPTZ,
                         conditions_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX ix_coupons_active ON coupons (start_at, end_at);

-- ================================
-- 14) tradeins
-- ================================
CREATE TABLE tradeins (
                          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id         BIGINT REFERENCES users(id) ON DELETE SET NULL,
                          brand           VARCHAR(100) NOT NULL,
                          model           VARCHAR(100) NOT NULL,
                          storage_gb      INTEGER CHECK (storage_gb > 0),
                          condition_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
                          offered_price   NUMERIC(12,2) CHECK (offered_price >= 0),
                          status          VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','quoted','accepted','rejected','cancelled')),
                          appointment_at  TIMESTAMPTZ
);
CREATE INDEX ix_tradeins_user_status ON tradeins(user_id, status);

-- ================================
-- 15) repairs
-- ================================
CREATE TABLE repairs (
                         id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_id        BIGINT REFERENCES users(id) ON DELETE SET NULL,
                         device_info    TEXT NOT NULL,
                         fault_desc     TEXT,
                         estimated_cost NUMERIC(12,2) CHECK (estimated_cost >= 0),
                         status         VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','diagnosing','in_progress','done','cancelled')),
                         warranty_days  INTEGER NOT NULL DEFAULT 0 CHECK (warranty_days >= 0)
);
CREATE INDEX ix_repairs_user_status ON repairs(user_id, status);

-- ================================
-- 16) events_audit
-- ================================
CREATE TABLE events_audit (
                              id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              actor_id   BIGINT REFERENCES users(id) ON DELETE SET NULL,
                              action     VARCHAR(50) NOT NULL,
                              entity     VARCHAR(50) NOT NULL,
                              entity_id  BIGINT,
                              meta_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
                              created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_entity ON events_audit(entity, entity_id, created_at DESC);
