SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;
COMMENT ON EXTENSION hstore IS 'data type for storing sets of (key, value) pairs';
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;
COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';
SET default_tablespace = '';
SET default_table_access_method = heap;
CREATE TABLE public.addresses (
    id uuid NOT NULL,
    address_line character varying(255) NOT NULL,
    city_code character varying(100) NOT NULL,
    city_name character varying(100) NOT NULL,
    district_code character varying(100),
    district_name character varying(100),
    full_name character varying(100) NOT NULL,
    is_default boolean NOT NULL,
    is_warehouse boolean NOT NULL,
    phone character varying(20) NOT NULL,
    ward_code character varying(100) NOT NULL,
    ward_name character varying(100) NOT NULL,
    user_id uuid NOT NULL
);
ALTER TABLE public.addresses OWNER TO tungnt;
CREATE TABLE public.blogs (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    modified_at timestamp(6) with time zone NOT NULL,
    author character varying(255),
    content text,
    image_url text,
    title character varying(255),
    view_count bigint NOT NULL,
    created_by uuid,
    modified_by uuid
);
ALTER TABLE public.blogs OWNER TO tungnt;
CREATE TABLE public.brands (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone,
    logo_url character varying(255),
    name character varying(100) NOT NULL
);


ALTER TABLE public.brands OWNER TO tungnt;

--
-- TOC entry 223 (class 1259 OID 16743)
-- Name: cart_items; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.cart_items (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    product_color_id uuid NOT NULL,
    qty integer NOT NULL,
    total_price numeric(12,2) NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.cart_items OWNER TO tungnt;

--
-- TOC entry 224 (class 1259 OID 16748)
-- Name: categories; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.categories (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    modified_at timestamp(6) with time zone NOT NULL,
    description character varying(255),
    image character varying(255),
    is_active boolean NOT NULL,
    name character varying(100) NOT NULL,
    created_by uuid,
    modified_by uuid
);


ALTER TABLE public.categories OWNER TO tungnt;

--
-- TOC entry 225 (class 1259 OID 16755)
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.chat_messages (
    id uuid NOT NULL,
    ai_confidence_score double precision,
    content text NOT NULL,
    created_at timestamp(6) with time zone,
    is_read boolean,
    sender_type character varying(255) NOT NULL,
    conversation_id uuid NOT NULL,
    CONSTRAINT chat_messages_sender_type_check CHECK (((sender_type)::text = ANY ((ARRAY['USER'::character varying, 'BOT'::character varying, 'AGENT'::character varying])::text[])))
);


ALTER TABLE public.chat_messages OWNER TO tungnt;

--
-- TOC entry 227 (class 1259 OID 16764)
-- Name: comments; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    author character varying(255),
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    target_id bigint NOT NULL,
    target_type character varying(255) NOT NULL,
    parent_id bigint
);


ALTER TABLE public.comments OWNER TO tungnt;

--
-- TOC entry 226 (class 1259 OID 16763)
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: tungnt
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16771)
-- Name: conversations; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.conversations (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    modified_at timestamp(6) with time zone NOT NULL,
    last_message_at timestamp(6) with time zone,
    session_id character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    created_by uuid,
    modified_by uuid,
    user_id uuid,
    CONSTRAINT conversations_status_check CHECK (((status)::text = ANY ((ARRAY['BOT_ACTIVE'::character varying, 'PENDING_HUMAN'::character varying, 'HUMAN_ACTIVE'::character varying, 'CLOSED'::character varying])::text[])))
);


ALTER TABLE public.conversations OWNER TO tungnt;

--
-- TOC entry 229 (class 1259 OID 16779)
-- Name: invalidate_token; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.invalidate_token (
    id character varying(255) NOT NULL,
    expiry_date timestamp(6) without time zone
);


ALTER TABLE public.invalidate_token OWNER TO tungnt;

--
-- TOC entry 230 (class 1259 OID 16784)
-- Name: knowledge_base; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.knowledge_base (
    id uuid NOT NULL,
    content text NOT NULL,
    topic character varying(255) NOT NULL
);


ALTER TABLE public.knowledge_base OWNER TO tungnt;

--
-- TOC entry 231 (class 1259 OID 16791)
-- Name: order_items; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.order_items (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    qty integer NOT NULL,
    snapshot_product_color character varying(255),
    snapshot_product_media_url character varying(255),
    snapshot_product_model character varying(255),
    snapshot_product_name character varying(255),
    total_price numeric(12,2) NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    warranty_until date,
    order_id uuid NOT NULL,
    product_item_id uuid NOT NULL
);


ALTER TABLE public.order_items OWNER TO tungnt;

--
-- TOC entry 232 (class 1259 OID 16798)
-- Name: orders; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.orders (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    modified_at timestamp(6) with time zone NOT NULL,
    code character varying(50) NOT NULL,
    payment_method character varying(20) NOT NULL,
    payment_status character varying(20) NOT NULL,
    shipping_fee numeric(12,2) NOT NULL,
    snapshot_address character varying(255),
    snapshot_shipping_full_name character varying(255),
    snapshot_shipping_phone character varying(255),
    status character varying(20) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    created_by uuid,
    modified_by uuid,
    shipping_address_id uuid,
    user_id uuid NOT NULL,
    CONSTRAINT orders_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['cod'::character varying, 'bank'::character varying, 'e_wallet'::character varying, 'card'::character varying])::text[]))),
    CONSTRAINT orders_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['unpaid'::character varying, 'paid'::character varying, 'refunded'::character varying])::text[]))),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'paid'::character varying, 'processing'::character varying, 'shipped'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'refunded'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO tungnt;

--
-- TOC entry 233 (class 1259 OID 16808)
-- Name: permission; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.permission (
    name character varying(255) NOT NULL,
    created_at timestamp(6) with time zone,
    description character varying(255)
);


ALTER TABLE public.permission OWNER TO tungnt;

--
-- TOC entry 234 (class 1259 OID 16815)
-- Name: product_colors; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.product_colors (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    hex_code character varying(7),
    name character varying(50) NOT NULL,
    qty_available integer,
    product_model_id uuid NOT NULL
);


ALTER TABLE public.product_colors OWNER TO tungnt;

--
-- TOC entry 235 (class 1259 OID 16820)
-- Name: product_diagnostics; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.product_diagnostics (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    modified_at timestamp(6) with time zone NOT NULL,
    additional_notes character varying(255),
    battery_health numeric(5,2),
    button_damage boolean,
    charging_port_damage boolean,
    dead_pixels numeric(5,2) NOT NULL,
    dents numeric(5,2) NOT NULL,
    display_failure numeric(5,2) NOT NULL,
    display_lines numeric(5,2) NOT NULL,
    edge_dings numeric(5,2) NOT NULL,
    estimated_repair_cost numeric(12,2),
    front_camera_damage boolean,
    microphone_damage boolean,
    overall_assessment character varying(255),
    rear_camera_damage boolean,
    repair_recommendations character varying(255),
    scratches numeric(5,2) NOT NULL,
    screen_cracks numeric(5,2) NOT NULL,
    speaker_damage boolean,
    status character varying(20),
    test_date date,
    total_depreciation numeric(5,2) NOT NULL,
    wifi_bluetooth_issue boolean,
    created_by uuid,
    modified_by uuid,
    product_item_id uuid NOT NULL,
    staff_id uuid,
    CONSTRAINT product_diagnostics_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'tested'::character varying, 'cancelled'::character varying])::text[])))
);


ALTER TABLE public.product_diagnostics OWNER TO tungnt;

--
-- TOC entry 246 (class 1259 OID 41294)
-- Name: product_embeddings; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.product_embeddings (
    product_item_id uuid NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    embedding public.vector(768) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.product_embeddings OWNER TO tungnt;

--
-- TOC entry 236 (class 1259 OID 16828)
-- Name: product_items; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.product_items (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    modified_at timestamp(6) with time zone NOT NULL,
    base_price numeric(12,2) NOT NULL,
    battery_capacity integer,
    bluetooth character varying(255),
    charging_port character varying(255),
    charging_power integer,
    charging_technology character varying(255),
    chipset character varying(255),
    compare_price numeric(12,2),
    cpu character varying(255),
    description text,
    dimensions character varying(255),
    front_camera character varying(255),
    front_video character varying(255),
    gps character varying(255),
    gpu character varying(255),
    name character varying(255),
    network character varying(255),
    nfc character varying(255),
    operating_system character varying(255),
    rear_camera character varying(255),
    rear_camera_features character varying(255),
    rear_video character varying(255),
    refresh_rate integer,
    release_time character varying(255),
    screen_features character varying(255),
    screen_resolution character varying(255),
    screen_size double precision,
    screen_technology character varying(255),
    screen_type character varying(255),
    sell_price numeric(12,2) NOT NULL,
    sensors character varying(255),
    sim_type character varying(255),
    status integer DEFAULT 0 NOT NULL,
    water_resistance character varying(255),
    weight integer,
    wifi character varying(255),
    created_by uuid,
    modified_by uuid,
    product_id uuid NOT NULL,
    is_trade_in integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.product_items OWNER TO tungnt;

--
-- TOC entry 237 (class 1259 OID 16836)
-- Name: product_media; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.product_media (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    is_primary boolean NOT NULL,
    public_id character varying(255) NOT NULL,
    sort_order integer NOT NULL,
    type character varying(10),
    url character varying(255) NOT NULL,
    product_item_id uuid NOT NULL,
    CONSTRAINT product_media_type_check CHECK (((type)::text = ANY ((ARRAY['image'::character varying, 'video'::character varying])::text[])))
);


ALTER TABLE public.product_media OWNER TO tungnt;

--
-- TOC entry 238 (class 1259 OID 16844)
-- Name: product_models; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.product_models (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(255),
    grade character(1),
    name character varying(100) NOT NULL,
    ram_gb integer,
    rom_gb integer NOT NULL,
    product_item_id uuid,
    CONSTRAINT product_models_grade_check CHECK ((grade = ANY (ARRAY['A'::bpchar, 'B'::bpchar, 'C'::bpchar, 'D'::bpchar])))
);


ALTER TABLE public.product_models OWNER TO tungnt;

--
-- TOC entry 239 (class 1259 OID 16850)
-- Name: product_ratings; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.product_ratings (
    id uuid NOT NULL,
    content character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    rating integer NOT NULL,
    order_id uuid,
    product_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.product_ratings OWNER TO tungnt;

--
-- TOC entry 240 (class 1259 OID 16855)
-- Name: products; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.products (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    modified_at timestamp(6) with time zone NOT NULL,
    description text,
    name character varying(200) NOT NULL,
    status character varying(20) NOT NULL,
    warranty_months integer NOT NULL,
    created_by uuid,
    modified_by uuid,
    brand_id uuid NOT NULL,
    category_id uuid NOT NULL
);


ALTER TABLE public.products OWNER TO tungnt;

--
-- TOC entry 241 (class 1259 OID 16863)
-- Name: role; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.role (
    name character varying(255) NOT NULL,
    description character varying(255)
);


ALTER TABLE public.role OWNER TO tungnt;

--
-- TOC entry 242 (class 1259 OID 16870)
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.role_permissions (
    role_name character varying(255) NOT NULL,
    permissions_name character varying(255) NOT NULL
);


ALTER TABLE public.role_permissions OWNER TO tungnt;

--
-- TOC entry 243 (class 1259 OID 16877)
-- Name: tradeins; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.tradeins (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    modified_at timestamp(6) with time zone NOT NULL,
    appointment_at timestamp(6) with time zone,
    inspection_notes character varying(255),
    quoted_price numeric(12,2),
    status character varying(20) NOT NULL,
    created_by uuid,
    modified_by uuid,
    product_diagnostic_id uuid,
    product_item_id uuid NOT NULL,
    staff_id uuid,
    user_id uuid,
    CONSTRAINT tradeins_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'inspecting'::character varying, 'quoted'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'cancelled'::character varying, 'completed'::character varying])::text[])))
);


ALTER TABLE public.tradeins OWNER TO tungnt;

--
-- TOC entry 244 (class 1259 OID 16883)
-- Name: users; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    modified_at timestamp(6) with time zone NOT NULL,
    birth_date date,
    email character varying(100) NOT NULL,
    full_name character varying(100) NOT NULL,
    gender character varying(10),
    password character varying(255),
    phone character varying(20),
    status character varying(20) NOT NULL,
    created_by uuid,
    modified_by uuid,
    avatar_url character varying(255),
    CONSTRAINT users_gender_check CHECK (((gender)::text = ANY ((ARRAY['male'::character varying, 'female'::character varying, 'other'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'inactive'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO tungnt;

--
-- TOC entry 245 (class 1259 OID 16892)
-- Name: users_roles; Type: TABLE; Schema: public; Owner: tungnt
--

CREATE TABLE public.users_roles (
    user_id uuid NOT NULL,
    roles_name character varying(255) NOT NULL
);


ALTER TABLE public.users_roles OWNER TO tungnt;

--
-- TOC entry 3669 (class 2606 OID 16730)
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 3671 (class 2606 OID 16737)
-- Name: blogs blogs_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.blogs
    ADD CONSTRAINT blogs_pkey PRIMARY KEY (id);


--
-- TOC entry 3673 (class 2606 OID 16742)
-- Name: brands brands_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.brands
    ADD CONSTRAINT brands_pkey PRIMARY KEY (id);


--
-- TOC entry 3677 (class 2606 OID 16747)
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- TOC entry 3679 (class 2606 OID 16754)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 3683 (class 2606 OID 16762)
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- TOC entry 3685 (class 2606 OID 16770)
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- TOC entry 3687 (class 2606 OID 16778)
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);


--
-- TOC entry 3691 (class 2606 OID 16783)
-- Name: invalidate_token invalidate_token_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.invalidate_token
    ADD CONSTRAINT invalidate_token_pkey PRIMARY KEY (id);


--
-- TOC entry 3693 (class 2606 OID 16790)
-- Name: knowledge_base knowledge_base_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.knowledge_base
    ADD CONSTRAINT knowledge_base_pkey PRIMARY KEY (id);


--
-- TOC entry 3695 (class 2606 OID 16797)
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- TOC entry 3697 (class 2606 OID 16807)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 3701 (class 2606 OID 16814)
-- Name: permission permission_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (name);


--
-- TOC entry 3703 (class 2606 OID 16819)
-- Name: product_colors product_colors_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_colors
    ADD CONSTRAINT product_colors_pkey PRIMARY KEY (id);


--
-- TOC entry 3705 (class 2606 OID 16827)
-- Name: product_diagnostics product_diagnostics_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_diagnostics
    ADD CONSTRAINT product_diagnostics_pkey PRIMARY KEY (id);


--
-- TOC entry 3731 (class 2606 OID 41300)
-- Name: product_embeddings product_embeddings_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_embeddings
    ADD CONSTRAINT product_embeddings_pkey PRIMARY KEY (product_item_id);


--
-- TOC entry 3707 (class 2606 OID 16835)
-- Name: product_items product_items_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_items
    ADD CONSTRAINT product_items_pkey PRIMARY KEY (id);


--
-- TOC entry 3709 (class 2606 OID 16843)
-- Name: product_media product_media_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_media
    ADD CONSTRAINT product_media_pkey PRIMARY KEY (id);


--
-- TOC entry 3711 (class 2606 OID 16849)
-- Name: product_models product_models_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_models
    ADD CONSTRAINT product_models_pkey PRIMARY KEY (id);


--
-- TOC entry 3713 (class 2606 OID 16854)
-- Name: product_ratings product_ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_ratings
    ADD CONSTRAINT product_ratings_pkey PRIMARY KEY (id);


--
-- TOC entry 3715 (class 2606 OID 16862)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 3719 (class 2606 OID 16876)
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role_name, permissions_name);


--
-- TOC entry 3717 (class 2606 OID 16869)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (name);


--
-- TOC entry 3721 (class 2606 OID 16882)
-- Name: tradeins tradeins_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.tradeins
    ADD CONSTRAINT tradeins_pkey PRIMARY KEY (id);


--
-- TOC entry 3689 (class 2606 OID 16902)
-- Name: conversations uk4eys3jh7q11vkq6upqx8jvy93; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT uk4eys3jh7q11vkq6upqx8jvy93 UNIQUE (session_id);


--
-- TOC entry 3723 (class 2606 OID 16906)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 3725 (class 2606 OID 16908)
-- Name: users ukdu5v5sr43g5bfnji4vb8hg5s3; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone);


--
-- TOC entry 3699 (class 2606 OID 16904)
-- Name: orders ukgt3o4a5bqj59e9y6wakgk926t; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT ukgt3o4a5bqj59e9y6wakgk926t UNIQUE (code);


--
-- TOC entry 3675 (class 2606 OID 16898)
-- Name: brands ukoce3937d2f4mpfqrycbr0l93m; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.brands
    ADD CONSTRAINT ukoce3937d2f4mpfqrycbr0l93m UNIQUE (name);


--
-- TOC entry 3681 (class 2606 OID 16900)
-- Name: categories ukt8o6pivur7nn124jehx7cygw5; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);


--
-- TOC entry 3727 (class 2606 OID 16891)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3729 (class 2606 OID 16896)
-- Name: users_roles users_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_pkey PRIMARY KEY (user_id, roles_name);


--
-- TOC entry 3732 (class 2606 OID 16909)
-- Name: addresses fk1fa36y2oqhao3wgg2rw1pi459; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT fk1fa36y2oqhao3wgg2rw1pi459 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3776 (class 2606 OID 17134)
-- Name: users_roles fk2o0jvgh89lemvvo17cbqvdxaa; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fk2o0jvgh89lemvvo17cbqvdxaa FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3745 (class 2606 OID 16989)
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3774 (class 2606 OID 17124)
-- Name: users fk3aqdj6u2t0by2dj24m141utm; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk3aqdj6u2t0by2dj24m141utm FOREIGN KEY (modified_by) REFERENCES public.users(id);


--
-- TOC entry 3754 (class 2606 OID 17029)
-- Name: product_items fk3gegsnjqr0sr3ipk5vu75t21r; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_items
    ADD CONSTRAINT fk3gegsnjqr0sr3ipk5vu75t21r FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 3749 (class 2606 OID 16994)
-- Name: product_colors fk5e3feq1a5xhhhjcb4kqrujq4j; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_colors
    ADD CONSTRAINT fk5e3feq1a5xhhhjcb4kqrujq4j FOREIGN KEY (product_model_id) REFERENCES public.product_models(id);


--
-- TOC entry 3758 (class 2606 OID 17039)
-- Name: product_models fk5stnanp01xamgjt7ysy26rgc2; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_models
    ADD CONSTRAINT fk5stnanp01xamgjt7ysy26rgc2 FOREIGN KEY (product_item_id) REFERENCES public.product_items(id);


--
-- TOC entry 3740 (class 2606 OID 16949)
-- Name: conversations fk5uxcbsjes7nd38wm1qtsfaw28; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk5uxcbsjes7nd38wm1qtsfaw28 FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- TOC entry 3736 (class 2606 OID 16929)
-- Name: categories fk5yfru0au6kpyqs4tonky5vfne; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fk5yfru0au6kpyqs4tonky5vfne FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- TOC entry 3759 (class 2606 OID 17049)
-- Name: product_ratings fk6vmxt3km86rrgrslgy71ne3e5; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_ratings
    ADD CONSTRAINT fk6vmxt3km86rrgrslgy71ne3e5 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 3750 (class 2606 OID 17009)
-- Name: product_diagnostics fk6x1f1189358ofb0jslij1k7ks; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_diagnostics
    ADD CONSTRAINT fk6x1f1189358ofb0jslij1k7ks FOREIGN KEY (product_item_id) REFERENCES public.product_items(id);


--
-- TOC entry 3735 (class 2606 OID 16924)
-- Name: cart_items fk709eickf3kc0dujx3ub9i7btf; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk709eickf3kc0dujx3ub9i7btf FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3768 (class 2606 OID 17114)
-- Name: tradeins fk7kn24cah50babysn42kftur8t; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.tradeins
    ADD CONSTRAINT fk7kn24cah50babysn42kftur8t FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3733 (class 2606 OID 16919)
-- Name: blogs fk7s5yo1b4q40v1tpg6v862f35d; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.blogs
    ADD CONSTRAINT fk7s5yo1b4q40v1tpg6v862f35d FOREIGN KEY (modified_by) REFERENCES public.users(id);


--
-- TOC entry 3777 (class 2606 OID 17129)
-- Name: users_roles fk7tacasmhqivyolfjjxseeha5c; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fk7tacasmhqivyolfjjxseeha5c FOREIGN KEY (roles_name) REFERENCES public.role(name);


--
-- TOC entry 3769 (class 2606 OID 17104)
-- Name: tradeins fk9sktq0uvn90731d9g27ssr0ur; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.tradeins
    ADD CONSTRAINT fk9sktq0uvn90731d9g27ssr0ur FOREIGN KEY (product_item_id) REFERENCES public.product_items(id);


--
-- TOC entry 3762 (class 2606 OID 17069)
-- Name: products fka3a4mpsfdf4d2y6r8ra3sc8mv; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fka3a4mpsfdf4d2y6r8ra3sc8mv FOREIGN KEY (brand_id) REFERENCES public.brands(id);


--
-- TOC entry 3741 (class 2606 OID 16954)
-- Name: conversations fkaj8is4yh03smepx5w6w4dw8c7; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fkaj8is4yh03smepx5w6w4dw8c7 FOREIGN KEY (modified_by) REFERENCES public.users(id);


--
-- TOC entry 3755 (class 2606 OID 17024)
-- Name: product_items fkb9j5vc7x5m81l2y8ypnlt9gj0; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_items
    ADD CONSTRAINT fkb9j5vc7x5m81l2y8ypnlt9gj0 FOREIGN KEY (modified_by) REFERENCES public.users(id);


--
-- TOC entry 3743 (class 2606 OID 16964)
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- TOC entry 3760 (class 2606 OID 17044)
-- Name: product_ratings fkbkqsm18ig0pfrj5s9a0e87lj9; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_ratings
    ADD CONSTRAINT fkbkqsm18ig0pfrj5s9a0e87lj9 FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- TOC entry 3737 (class 2606 OID 16934)
-- Name: categories fkbxwpgyorhtg7fclpa7gagswc5; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fkbxwpgyorhtg7fclpa7gagswc5 FOREIGN KEY (modified_by) REFERENCES public.users(id);


--
-- TOC entry 3738 (class 2606 OID 16939)
-- Name: chat_messages fkc8ljv426x8fj9tcywei40stu9; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkc8ljv426x8fj9tcywei40stu9 FOREIGN KEY (conversation_id) REFERENCES public.conversations(id);


--
-- TOC entry 3766 (class 2606 OID 17084)
-- Name: role_permissions fkcppvu8fk24eqqn6q4hws7ajux; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkcppvu8fk24eqqn6q4hws7ajux FOREIGN KEY (role_name) REFERENCES public.role(name);


--
-- TOC entry 3746 (class 2606 OID 16979)
-- Name: orders fke0abpy849bl2ynw3468ksavvl; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fke0abpy849bl2ynw3468ksavvl FOREIGN KEY (modified_by) REFERENCES public.users(id);


--
-- TOC entry 3767 (class 2606 OID 17079)
-- Name: role_permissions fkf5aljih4mxtdgalvr7xvngfn1; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkf5aljih4mxtdgalvr7xvngfn1 FOREIGN KEY (permissions_name) REFERENCES public.permission(name);


--
-- TOC entry 3763 (class 2606 OID 17064)
-- Name: products fkgrk06220ryw810spdwd2rhvvl; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkgrk06220ryw810spdwd2rhvvl FOREIGN KEY (modified_by) REFERENCES public.users(id);


--
-- TOC entry 3770 (class 2606 OID 17094)
-- Name: tradeins fkgu4tljs0x4t3jtcx4pvknkd6x; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.tradeins
    ADD CONSTRAINT fkgu4tljs0x4t3jtcx4pvknkd6x FOREIGN KEY (modified_by) REFERENCES public.users(id);


--
-- TOC entry 3775 (class 2606 OID 17119)
-- Name: users fkibk1e3kaxy5sfyeekp8hbhnim; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkibk1e3kaxy5sfyeekp8hbhnim FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- TOC entry 3771 (class 2606 OID 17109)
-- Name: tradeins fkj4ldoqnt3lu80pqjme1c4vkc; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.tradeins
    ADD CONSTRAINT fkj4ldoqnt3lu80pqjme1c4vkc FOREIGN KEY (staff_id) REFERENCES public.users(id);


--
-- TOC entry 3734 (class 2606 OID 16914)
-- Name: blogs fkjidd8cjtc34c0i5h0f88x062t; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.blogs
    ADD CONSTRAINT fkjidd8cjtc34c0i5h0f88x062t FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- TOC entry 3772 (class 2606 OID 17089)
-- Name: tradeins fkjpjlp2b082540mmnbsen0wkw; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.tradeins
    ADD CONSTRAINT fkjpjlp2b082540mmnbsen0wkw FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- TOC entry 3751 (class 2606 OID 17004)
-- Name: product_diagnostics fkkevol9k02w1bf7q74qxnlpb84; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_diagnostics
    ADD CONSTRAINT fkkevol9k02w1bf7q74qxnlpb84 FOREIGN KEY (modified_by) REFERENCES public.users(id);


--
-- TOC entry 3744 (class 2606 OID 16969)
-- Name: order_items fkkiaxsuhi10m9s93gycq7uryyj; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkkiaxsuhi10m9s93gycq7uryyj FOREIGN KEY (product_item_id) REFERENCES public.product_items(id);


--
-- TOC entry 3764 (class 2606 OID 17059)
-- Name: products fkl0lce8i162ldn9n01t2a6lcix; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkl0lce8i162ldn9n01t2a6lcix FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- TOC entry 3739 (class 2606 OID 16944)
-- Name: comments fklri30okf66phtcgbe5pok7cc0; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fklri30okf66phtcgbe5pok7cc0 FOREIGN KEY (parent_id) REFERENCES public.comments(id);


--
-- TOC entry 3756 (class 2606 OID 17019)
-- Name: product_items fkm0dpcj9mbvutpj6x1i0lomqa1; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_items
    ADD CONSTRAINT fkm0dpcj9mbvutpj6x1i0lomqa1 FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- TOC entry 3747 (class 2606 OID 16984)
-- Name: orders fkmk6q95x8ffidq82wlqjaq7sqc; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkmk6q95x8ffidq82wlqjaq7sqc FOREIGN KEY (shipping_address_id) REFERENCES public.addresses(id);


--
-- TOC entry 3773 (class 2606 OID 17099)
-- Name: tradeins fkmokdst8x4sqe058lot3fdvxk7; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.tradeins
    ADD CONSTRAINT fkmokdst8x4sqe058lot3fdvxk7 FOREIGN KEY (product_diagnostic_id) REFERENCES public.product_diagnostics(id);


--
-- TOC entry 3765 (class 2606 OID 17074)
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- TOC entry 3742 (class 2606 OID 16959)
-- Name: conversations fkpltqvfcbkql9svdqwh0hw4g1d; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fkpltqvfcbkql9svdqwh0hw4g1d FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3752 (class 2606 OID 17014)
-- Name: product_diagnostics fkq0rix3a7eiq11p61d3w50iuin; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_diagnostics
    ADD CONSTRAINT fkq0rix3a7eiq11p61d3w50iuin FOREIGN KEY (staff_id) REFERENCES public.users(id);


--
-- TOC entry 3753 (class 2606 OID 16999)
-- Name: product_diagnostics fkq1sule7fyhd7o4aow9gbik4qy; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_diagnostics
    ADD CONSTRAINT fkq1sule7fyhd7o4aow9gbik4qy FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- TOC entry 3761 (class 2606 OID 17054)
-- Name: product_ratings fkrinkxs2nb4wouojjdsn4nn8g9; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_ratings
    ADD CONSTRAINT fkrinkxs2nb4wouojjdsn4nn8g9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3757 (class 2606 OID 17034)
-- Name: product_media fksnnxwag1i0v05gq90t64p1nxn; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.product_media
    ADD CONSTRAINT fksnnxwag1i0v05gq90t64p1nxn FOREIGN KEY (product_item_id) REFERENCES public.product_items(id);


--
-- TOC entry 3748 (class 2606 OID 16974)
-- Name: orders fktjwuphstqm46uffgc7l1r27a9; Type: FK CONSTRAINT; Schema: public; Owner: tungnt
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fktjwuphstqm46uffgc7l1r27a9 FOREIGN KEY (created_by) REFERENCES public.users(id);


-- Completed on 2026-02-02 22:32:10

--
-- PostgreSQL database dump complete
--

